---
title: "p8105_hw3_zw2975"
author: "Zhiyu Wei"
date: 2024-10-14
output: github_document
---

Setup

```{r setup, include = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(patchwork)
library(knitr)
library(sf)
library(lubridate)
library(stringr)
library(leaflet)
library(shiny)
library(leaflet.extras)
library(htmlwidgets)
library(rgeoda)
library(RColorBrewer)
library(classInt)
```


```{r load evictions data}
evic = read.csv("./data/evictions.csv")

uhf = st_read("./UHF_42_DOHMH_2009/UHF_42_DOHMH_2009.shp")
```

```{r rename and clean}
evic =janitor::clean_names(evic)

uhf = janitor::clean_names(uhf)

# change date format
evic$executed_date <- mdy(evic$executed_date)

# add year to data 
evic = evic |>
  mutate(year = format(executed_date, "%Y"))
```

#### EDA

```{r Eviction EDA}
# eviction by boroughs
evic |>
  group_by(borough) |>
  summarize(Num_evic = n())|>
  knitr::kable(col.names = c("Borough", "Number of Evictions"))

# evictions by year
evic |>
  group_by(year) |>
  summarize(num_evic = n()) |>
  knitr::kable(col.names = c("Year", "Number of Evictions"))

# by both
evic |>
  group_by(year, borough) |>
  summarize(num_evic = n()) |>
  knitr::kable(col.names = c("Year", "NYC boroughs", "Number of Evictions"))
```


```{r bar graphs}
# by borough
evic |>
  ggplot(aes(x = borough))+
  geom_bar() +
  labs(x ="NYC Boroughs",
        y = "Number of Evictions")

# by year
evic |>
  filter(!(year == 2025)) |>
  ggplot(aes(x = year))+
  geom_bar() +
  labs(x = "Year",
        y = "Number of Evictions")

# Stacked up by borough
evic|>
  group_by(year) %>%
  count(borough) %>%
  ggplot(aes(x = year, y = n, fill = borough)) +
  geom_col() +
  labs(x = "Year",
       y = "Number of Evictions")
  
```

#### write out the csv
```{r csv for evictions}
write.csv(evic, "./data/evictions_for_Qgis.csv")

# 2022 
evic_22 = evic |>
  filter(year == 2022)

write.csv(evic_22, "./data/eviction_2022.csv")
```

#### counting points
```{r point count}
#save coordinates as geometry
evic = evic |>
  na.omit()|>
  st_as_sf(coords = c("longitude","latitude"), crs = 4326)

# transform coordinate reference system
if (!st_crs(evic) == st_crs(uhf)) {

  # Transform evic to match uhf

  uhf_transform <- st_transform(uhf, st_crs(evic)) 
} 

# count points within uhf polygons for each year (until 2024)
uhf_evic_2017 <- uhf_transform |>
  na.omit() |>
  mutate(counts = lengths(st_intersects(geometry, evic |> filter(year == 2017))),
         year = 2017)

uhf_evic_2018 <- uhf_transform |>
  na.omit() |>
  mutate(counts = lengths(st_intersects(geometry, evic |> filter(year == 2018))),
         year = 2018)

uhf_evic_2019 <- uhf_transform |>
  na.omit() |>
  mutate(counts = lengths(st_intersects(geometry, evic |> filter(year == 2019))),
         year = 2019)

uhf_evic_2020 <- uhf_transform |>
  na.omit() |>
  mutate(counts = lengths(st_intersects(geometry, evic |> filter(year == 2020))),
         year = 2020)

uhf_evic_2021 <- uhf_transform |>
  na.omit() |>
  mutate(counts = lengths(st_intersects(geometry, evic |> filter(year == 2021))),
         year = 2021)

uhf_evic_2022 <- uhf_transform |>
  na.omit() |>
  mutate(counts = lengths(st_intersects(geometry, evic |> filter(year == 2022))),
         year = 2022)

uhf_evic_2023 <- uhf_transform |>
  na.omit() |>
  mutate(counts = lengths(st_intersects(geometry, evic |> filter(year == 2023))),
         year = 2023)

uhf_evic_2024 <- uhf_transform |>
  na.omit() |>
  mutate(counts = lengths(st_intersects(geometry, evic |> filter(year == 2024))),
         year = 2024)

# bind all years together
uhf_evic = rbind (uhf_evic_2019, uhf_evic_2020, uhf_evic_2021, uhf_evic_2022, uhf_evic_2023, uhf_evic_2024)

# check coordinate referencce system
st_crs(uhf_evic)

```

#### Using UHF

```{r uhf}
# Mapping with UHF polygons (see the 42 neighborhoods)
ggplot()+
  geom_sf(data = uhf)
```

#### Eviction Leaflet

Layer 1: Display dataset with pop-up

```{r Display dataset with pop-up}
# Rename variables 
uhf_evic = uhf_evic |> 
  rename("Neighborhood" = uhf_neigh,
         "Borough" = borough)

# Base tiles
leaflet() |> 
  addProviderTiles("CartoDB", group = "CartoDB")

#add multiple base maps
leaflet() |> 
  addProviderTiles("CartoDB", group = "CartoDB") |> 
  addProviderTiles("CartoDB.DarkMatterNoLabels", group = "CartoDB - Black") 


# Control layer
leaflet() |>  
  addProviderTiles("CartoDB", group = "CartoDB") |> 
  addProviderTiles("CartoDB.DarkMatterNoLabels", group = "CartoDB - Black") |> 
  addLayersControl(baseGroups = c("CartoDB", "CartoDB - Black")) 
######

# Specify location of interest
leaflet() |>  
  addProviderTiles("CartoDB", group = "CartoDB") |> 
  addProviderTiles("CartoDB.DarkMatterNoLabels", group = "CartoDB - Black") |> 
  setView(lng = -74.006, lat = 40.7128, zoom = 10) |>  # Coordinates of NYC
  addLayersControl(baseGroups = c("CartoDB", "CartoDB - Black")) 


# Assign it to an object
leaflet() |>  
  addProviderTiles("CartoDB", group = "CartoDB") |> 
  addProviderTiles("CartoDB.DarkMatterNoLabels", group = "CartoDB - Black") |> 
  setView(lng = -74.006, lat = 40.7128, zoom = 10) |>  # Coordinates of NYC
  addLayersControl(baseGroups = c("CartoDB", "CartoDB - Black")) -> map_tiles
```


#### Add choropleth layer 
### need to tailor for each year and then make different layer for each


``` {R choropleth}
# Continious Color palette 
pal_uhf_evic <- colorNumeric("Blu", 
                     domain = uhf_evic$counts,
                     reverse = FALSE)
# List of datasets
years <- 2017:2024
datasets <- lapply(years, function(year) get(paste0("uhf_evic_", year)))

# Generate color palettes dynamically
palettes <- lapply(datasets, function(data) {
  colorNumeric("Blu", domain = data$counts, reverse = FALSE)
})

# Assign palettes to variables dynamically
names(palettes) <- paste0("pal_uhf_evic_", years)
list2env(palettes, envir = .GlobalEnv)  # Export palettes to global environment

###########

# Add the layer 
map_tiles |> 
  addPolygons(data = uhf_evic,
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic(counts),
              fillOpacity = 0.7,
              label = ~Neighborhood) |> 
  addLegend(pal = pal_uhf_evic,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") 

map_tiles |> 
  addPolygons(data = uhf_evic_2017,
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2017(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
  addLegend(pal = pal_uhf_evic,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") 

####

# Add layers for all years (2017 - 2024, and all years)
map_tiles <- map_tiles |>
  addPolygons(data = uhf_evic,
              group = "Total Evictions (2017 - 2024)",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic(counts),
              fillOpacity = 0.7,
              label = ~Neighborhood) |> 
  addPolygons(data = uhf_evic_2017,
              group = "Evictions 2017",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2017(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
    addPolygons(data = uhf_evic_2018,
              group = "Evictions 2018",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2018(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
    addPolygons(data = uhf_evic_2019,
              group = "Evictions 2019",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2019(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
    addPolygons(data = uhf_evic_2020,
              group = "Evictions 2020",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2020(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
    addPolygons(data = uhf_evic_2021,
              group = "Evictions 2021",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2021(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
     addPolygons(data = uhf_evic_2022,
              group = "Evictions 2022",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2022(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
     addPolygons(data = uhf_evic_2023,
              group = "Evictions 2023",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2023(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
    addPolygons(data = uhf_evic_2024,
              group = "Evictions 2024",
              color = "white",
              weight = 1,
              fillColor = ~pal_uhf_evic_2024(counts),
              fillOpacity = 0.7,
              label = ~uhf_neigh) |> 
# add legend
   addLegend(pal = pal_uhf_evic,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") |> 
  addLegend(pal = pal_uhf_evic_2017,
            values = uhf_evic_2017$counts,
            title = "Number of Evictions 2017",
            position = "bottomright") |> 
  addLegend(pal = pal_uhf_evic_2018,
            values = uhf_evic_2018$counts,
            title = "Number of Evictions 2018",
            position = "bottomright") |> 
  addLegend(pal = pal_uhf_evic_2019,
            values = uhf_evic_2019$counts,
            title = "Number of Evictions 2019",
            position = "bottomright") |> 
  addLegend(pal = pal_uhf_evic_2020,
            values = uhf_evic_2020$counts,
            title = "Number of Evictions 2020",
            position = "bottomright") |> 
  addLegend(pal = pal_uhf_evic_2021,
            values = uhf_evic_2021$counts,
            title = "Number of Evictions 2021",
            position = "bottomright") |> 
  addLegend(pal = pal_uhf_evic_2022,
            values = uhf_evic_2022$counts,
            title = "Number of Evictions 2022",
            position = "bottomright") |> 
  addLegend(pal = pal_uhf_evic_2023,
            values = uhf_evic_2023$counts,
            title = "Number of Evictions 2023",
            position = "bottomright") |> 
  addLegend(pal = pal_uhf_evic_2024,
            values = uhf_evic_2024$counts,
            title = HTML("<span style='font-size:14px;'>Number of Evictions 2024</span>"),
            position = "bottomright") |>
  
  addLayersControl(
    baseGroups = c("Total Evictions (2017 - 2024)", "Evictions 2017", "Evictions 2018", "Evictions 2019", "Evictions 2020", "Evictions 2021", "Evictions 2022", "Evictions 2023", "Evictions 2024"),
    options = layersControlOptions(collapsed = FALSE)
  ) |>

hideGroup(c("Total Evictions (2017 - 2024)", "Evictions 2017", "Evictions 2018", "Evictions 2019", "Evictions 2020", "Evictions 2021", "Evictions 2022", "Evictions 2023", "Evictions 2024"))


map_tiles
####


#############
# Add polygons for each year with grouped legends
years <- 2017:2024

for (year in years) {
  map_tiles <- map_tiles |>
    addPolygons(
      data = get(paste0("uhf_evic_", year)),  # Dynamically get the dataset
      group = paste0("Evictions ", year),
      color = "white",
      weight = 1,
      fillColor = ~get(paste0("pal_uhf_evic_", year))(counts),  # Dynamic palette
      fillOpacity = 0.7,
      label = ~uhf_neigh
    ) |>
    addLegend(
      pal = get(paste0("pal_uhf_evic_", year)),
      values = get(paste0("uhf_evic_", year))$counts,
      title = HTML(paste0("<span style='font-size:14px;'>Number of Evictions ", year, "</span>")),
      position = "bottomright",
      group = paste0("Evictions ", year)
    )
}

# Add polygons for total evictions
map_tiles <- map_tiles |>
  addPolygons(
    data = uhf_evic,
    group = "Total Evictions (2017 - 2024)",
    color = "white",
    weight = 1,
    fillColor = ~pal_uhf_evic(counts),
    fillOpacity = 0.7,
    label = ~Neighborhood
  ) |>
  addLegend(
    pal = pal_uhf_evic,
    values = uhf_evic$counts,
    title = "Number of Evictions (2017 - 2024)",
    position = "bottomright",
    group = "Total Evictions (2017 - 2024)"
  )

# Add layer control
map_tiles <- map_tiles |>
  addLayersControl(
    baseGroups = c("Total Evictions (2017 - 2024)", paste0("Evictions ", years)),
    options = layersControlOptions(collapsed = FALSE)
  ) |>
  hideGroup(c("Total Evictions (2017 - 2024)", paste0("Evictions ", years)))

# Render map
map_tiles

#################

# Generate equal quantiles (5 classes)
quantile_breaks <- classIntervals(uhf_evic$counts, n = 5, style = "quantile")

# View the break points
print(quantile_breaks$brks)

# 0.0   22.0   77.4  161.0  342.6 1189.0

pal_uhf_evic2 <- colorBin(palette = "Blu",             
                      domain = uhf_evic$counts,   
                      bins = c(0.0, 22.0,  77.4, 161.0, 342.6, 1189.0),                     
                      reverse = FALSE)

map_tiles |> 
  addPolygons(data = uhf_evic,
              color = "black",
              weight = 1,
              fillColor = ~pal_uhf_evic2(counts),
              fillOpacity = 0.7,
              label = ~Neighborhood) |> 
  addLegend(pal = pal_uhf_evic2,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") 


# Add pop-up
map_tiles |> 
  addPolygons(data = uhf_evic,
              color = "black",
              weight = 1,
              fillColor = ~pal_uhf_evic2(counts),
              fillOpacity = 0.7,
              label = ~Neighborhood,
              popup = ~paste(
                             Neighborhood, 
                             counts,
                             year
                             )) |> 
  addLegend(pal = pal_uhf_evic2,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") 


# Add labels and line breaks 
map_tiles |> 
  addPolygons(data = uhf_evic,
              color = "black",
              weight = 1,
              fillColor = ~pal_uhf_evic2(counts),
              fillOpacity = 0.7,
              label = ~Neighborhood,
              popup = ~paste(
                      "<b>Borough:</b>", Borough, "<br>",
                      "<b>Neighborhood:</b>", Neighborhood,"<br>",
                      "<b>Number of Evictions:</b>", counts,"<br>",
                      )) |> 
  addLegend(pal = pal_uhf_evic2,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") 


# Add the layer 
map_tiles |> 
  addPolygons(data = uhf_evic,
              color = "black",
              weight = 1,
              fillColor = ~pal_uhf_evic2(counts),
              fillOpacity = 0.7,
              label = ~Neighborhood,
              popup = ~paste(
                "<div style='font-family: Roboto; font-size: 12px; line-height: 1.4;'>",
                "<div style='font-size: 12px; font-weight: bold; color: #d9534f;'><b>Neighborhood:</b> ",  Neighborhood,"<br>",
                      "<b>Expenditures on Preventative Health Programs

:</b>", counts,"<br>",
                      "<b>Population who reside in rural places:</b>", PCT_RUR,"%<br>",
                      "<b>Population falls under the poverty line:</b>", PCT_POV,"%<br>",
                      "<b>Population with BA degrees:</b>", PCT_BA,"%<br>",
                      "<b>Population who are White:</b>", PCT_WH,"%<br>" ,
                "</div>")) |> 
  addLegend(pal = pal_uhf_evic2,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") 
```

## Layer 2: Display statistically significant High-High and Low-Low clusters

```{r clusters layers}
#Load bivariate shape file
clusters <-  st_read("./data/US_CTY_PreventativeHealthExp.shp") |>
  filter(LISA_CL == 1 | LISA_CL ==2) |>
  mutate(cluster = if_else(LISA_CL == 1, "High - High", "Low - Low", NA_character_))

#re project
clusters <- st_transform(clusters, crs = 4326)

# Add the clusters 
pal_cluster <- colorFactor(palette = c("darkred","darkblue"),
                           domain = clusters$cluster)
map_tiles |> 
  addPolygons(data = uhf_evic,
              color = "black",
              weight = 1,
              fillColor = ~pal_uhf_evic2(counts),
              fillOpacity = 0.7,
              label = ~Neighborhood,
              popup = ~paste(
                "<div style='font-family: Roboto; font-size: 12px; line-height: 1.4;'>",
                "<div style='font-size: 12px; font-weight: bold; color: #d9534f;'><b>Neighborhood:</b> ",  Neighborhood,"<br>",
                      "<b>Expenditures on Preventative Health Programs

:</b>", counts,"<br>",
                      "<b>Population who reside in rural places:</b>", PCT_RUR,"%<br>",
                      "<b>Population falls under the poverty line:</b>", PCT_POV,"%<br>",
                      "<b>Population with BA degrees:</b>", PCT_BA,"%<br>",
                      "<b>Population who are White:</b>", PCT_WH,"%<br>" ,
                "</div>")) |> 
  addLegend(pal = pal_uhf_evic2,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") |> 
  addPolygons(data = clusters,
             color = ~pal_cluster(cluster),
             weight = 2,
             fillColor = NA,
             popup = ~paste(cluster, "<br>"),
             group = "Clusters") |> 
  addLayersControl(baseGroups = c("CartoDB", "CartoDB - Black"),
                   overlayGroups = c("Number of Evictions", "Clusters"), 
                   options = layersControlOptions(collapsed = FALSE))

#### Prepare map for export ----
map_tiles |> 
  addPolygons(data = uhf_evic,
              color = "black",
              weight = 1,
              fillColor = ~pal_uhf_evic2(counts),
              fillOpacity = 0.7,
              label = ~Neighborhood,
              popup = ~paste(
                "<div style='font-family: Roboto; font-size: 12px; line-height: 1.4;'>",
                "<div style='font-size: 12px; font-weight: bold; color: #d9534f;'><b>Neighborhood:</b> ",  Neighborhood,"<br>",
                      "<b>Expenditures on Preventative Health Programs

:</b>", counts,"<br>",
                      "<b>Population who reside in rural places:</b>", PCT_RUR,"%<br>",
                      "<b>Population falls under the poverty line:</b>", PCT_POV,"%<br>",
                      "<b>Population with BA degrees:</b>", PCT_BA,"%<br>",
                      "<b>Population who are White:</b>", PCT_WH,"%<br>" ,
                "</div>")) |> 
  addLegend(pal = pal_uhf_evic2,
            values = uhf_evic$counts,
            title = "Number of Evictions",
            position = "bottomright") |> 
  addPolygons(data = clusters,
             color = ~pal_cluster(cluster),
             weight = 2,
             fillColor = NA,
             popup = ~paste(cluster, "<br>"),
             group = "Clusters") |> 
  addLayersControl(baseGroups = c("CartoDB", "CartoDB - Black"),
                   overlayGroups = c("Number of Evictions", "Clusters"), 
                   options = layersControlOptions(collapsed = FALSE)) -> Section4_map

# Save interactive maps 
saveWidget(eviction,
           file = "eviction_choropleth.html")


```


