---
title: "eviction/ejectment"
output: html_document
date: "2025-01-30"
---

#### Setup

```{r setup, include = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(patchwork)
library(knitr)
library(sf)
library(lubridate)
library(stringr)
library(leaflet)
library(shiny)
library(leaflet.extras)
library(htmlwidgets)
library(rgeoda)
library(RColorBrewer)
library(classInt)
```

#### read in dataset

```{r no ejectment}
evic = read.csv ("./data/evictions_for_Qgis.csv")

```

#### filter

```{r filter data}
evic_wo_eject = evic |>
  filter(!(ejectment == "Ejectment"))

evic_possess = evic_wo_eject |>
  filter(eviction_legal_possession == "Possession")

evic_evic = evic_wo_eject |>
  filter(eviction_legal_possession == "Eviction")

# for 2022
possess_22 = evic_possess |>
  filter(year == 2022)

evic_22_evic = evic_evic |>
  filter(year == 2022)

non_eject_22 = evic_wo_eject |>
  filter(year == 2022)
```

#### write out csv for GIS

```{r csv writing}
write.csv(possess_22, "./data/posses_22.csv")

write.csv(evic_22_evic, "./data/evic_22.csv")

write.csv(non_eject_22, "./data/non_eject_22.csv")

write.csv(evic_evic,
          "./data/evic_w_evictions.csv")

write.csv(evic_possess, "./data/evic_possess.csv")

write.csv(evic_wo_eject, "./data/evic_wo_eject.csv")

```

#### EDA

```{r EDA}
evic |>
  group_by(ejectment) |>
  summarize(Num_evic = n())|>
  knitr::kable(col.names = c("Ejectment", "Number of evictions"))

evic |>
  group_by(eviction_legal_possession) |>
  summarize(num_evic = n()) |>
  knitr::kable(col.names = c("Legal Possession","Number of Evictions"))

uhf_evic = st_read("./data/uhf_evic.shp")


uhf_evic |>
  select(year, uhf_neigh, eviction_legal_possession) %>%
  filter(eviction_legal_possession == "Eviction")
```

